DATA:
  DATASET: imagenet
  DATA_PATH: /srv/datasets/ImageNet
MODEL:
  TYPE: biswin
  NAME: biswin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    BIDIRECTIONAL_ATTENTION_LOCATIONS: [0]
    BIDIRECTION_ATTENTION_APPLY_NORM: True
TRAIN:
  ENFORCE_ATTENTION_ORTHONOGALITY: False
  ORTHOGONALITY_LAMBDA: 0.
  ALL_ORTHOGONALITY_LAMBDA: 0.
  BISA_LAMBDA_REGIME: (0., 50)
FINETUNING:
  APPLY_FINETUNING: False
  # BASE_MODEL: /srv/share4/gstoica3/checkpoints/swin_transformer/swin_tiny_patch4_window7_224/baseline_fp32/ckpt_epoch_294.pth
  # BASE_MODEL: /srv/share4/gstoica3/checkpoints/ContinualLearningHybridBaseFirstStageHead/biswin_tiny_patch4_window7_224/CorrectTransposeSoftmaxSelectionLambdaMatrix/ckpt_epoch_3.pth
  FREEZE_BASE: False
  STOP_EPOCH: 300
  TRAINABLES: head
  BASELINE_USES_SWIN_CFG: False