DATA:
  DATASET: imagenet
  DATA_PATH: /srv/datasets/ImageNet
MODEL:
  TYPE: biswin
  NAME: biswin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
    REVERSE_ATTENTION_LOCATIONS: [0]
    ALTERED_ATTENTION:
      TYPE: 'reverse'
      REDUCE_REVERSE: True
      REVERSE_ACTIVATION: 'gelu'