DATA:
  DATASET: cifar100
  DATA_PATH: /nethome/gstoica3/research/pytorch-cifar100/data/cifar-100-python
MODEL:
  TYPE: gsaswin
  NAME: biswin_tiny_patch4_window7_224_cifar100
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    BIDIRECTIONAL_ATTENTION_LOCATIONS: [0]
    BIDIRECTION_ATTENTION_APPLY_NORM: False
TRAIN:
  ORTHOGONALITY_LAMBDA: .0
  ALL_ORTHOGONALITY_LAMBDA: .0
  BISA_LAMBDA_REGIME: (100., 300)
  EPOCHS: 300
  WARMUP_EPOCHS: 20
FINETUNING:
  APPLY_FINETUNING: False
  BASE_MODEL: /srv/share4/gstoica3/checkpoints/FineTuneSwinReverseHeadBaseCifarFirstStage/biswin_tiny_patch4_window7_224_cifar100/StopEpoch150DiffNought1/ckpt_epoch_144.pth
  FREEZE_BASE: False
  STOP_EPOCH: 450
  # DIFF_BOUND: .5
  TRAINABLES: head
  BASELINE_USES_SWIN_CFG: False
TUNE_PARAMETERS:
  APPLY_TUNE: False
  WARMUP_EPOCHS: [10, 20, 30]
  WEIGHT_DECAY: [0.05, .1, .2]
  BASE_LR: [5e-4, 3e-4, 1e-4]
  WARMUP_LR: [5e-7, 5e-6]
  MIN_LR: [5e-6]
 